

```{r}
library(tidyverse)
library(dplyr)

install.packages('gclus')
install.packages('usmap')

library(gclus)

library(broom)

library(patchwork)

library(sandwich)
library(lmtest)

```

```{r}
setwd(".")
data <- read.csv("Selected_Data_V2.csv", strip.white=TRUE)
data_fips <- read.csv("vaccines.csv", strip.white=TRUE)
```

```{r}
head(data)
head(data_fips)
# state_check = select(data, "County", "TotPop", "State", "Dose1Pct")
# data_frame(state_check)
# new_df = select(state_check, state_check$State == "AL")
# new_df

# no_vaccine_check = select(data, "County", "TotPop", "State", "Dose1Pct")
# no_vaccine_check = subset(no_vaccine_check, Dose1Pct == 0)
```

The data that we are trying to operationalize is:
- vaccination rate: `Administered_Dose1_Pop_Pct`
- car access: (`Total.Households`-`No.vehicle.available`)/`Total.Households // Fraction of households with at least 1 car


```{r}

hist(data$CarPct, xlim=c(80,100), breaks=60)
hist(data$Dose1Pct)

summary_cars = summary(data$CarPct)
summary_vaccine = summary(data$Dose1Pct)

#Potential issue with some counties showing no vaccinations

#CarPct distribution

```

```{r}
#Summary statistics and error investigation
summary_cars
summary_vaccine
nrow(data)
sum(data$Dose1Pct == 0)
sum(data$TripsOver100PerCap > 0, na.rm = TRUE)
```

```{r}

#EDA on errors / abnormalities in original data
no_vaccine_check = select(data, "County", "TotPop", "State", "Dose1Pct")
no_vaccine_check = subset(no_vaccine_check, Dose1Pct == 0)

no_vaccine_check
# view(no_vaccine_check)

view(data)
```


```{r}
plot(data$TripsOver250PerCap,data$Dose1Pct)


```



```{r}
install.packages("corrplot")


#Chart Compare
pairs(~TripsOver250PerCap + CarPct + IncomePerCap + Dose1Pct, data=data)


```

```{r}

#Prep data for US Mapping
names(data_fips)[names(data_fips) == 'Recip_County'] <- 'County'

data2 <- merge(data,data_fips,by = "County")
names(data2)[names(data2) == 'FIPS'] <- 'fips'
data_fips
data
data2
library(usmap)
library(ggplot2)

#US map of vaccination rate
plot_usmap("counties", data = data2, values = "Dose1Pct", exclude = c("TX", "AK", "HI")) +
   labs(title = "Vaccination Rate by County (Excluding non-reporting counties)", subtitle = "Do counties with a higher vaccination rate have more travel?") +  ggplot2::scale_fill_continuous(low = "light blue", high = "dark blue", name = "Vaccination rate") +
  theme(legend.position = "right")
  
```

```{r}
#Plot USA trips
plot_usmap("counties", data = data2, values = "TripsOver250PerCap", exclude = c("AK", "HI")) +
   labs(title = "Trips over 250 miles per capita", subtitle = "Do counties with a higher vaccination rate have more travel?") +  ggplot2::scale_fill_continuous(low = "light blue", high = "dark blue", name = "Trips per capita") +
  theme(legend.position = "right")


  
```


```{r}
#Plot California
plot_usmap("counties", include = c("CA"), data = data2, values = "TripsOver250PerCap") +  ggplot2::scale_fill_continuous(low = "light blue", high = "dark blue", name = "Trips over 250 miles per capita") +
  theme(legend.position = "right")
plot_usmap("counties", include = c("CA"), data = data2, values = "Dose1Pct") +  ggplot2::scale_fill_continuous(low = "light blue", high = "dark blue", name = "Vaccination rate (%)") +
  theme(legend.position = "right")
```



```{r}

model  = lm(TripsOver250PerCap ~ Dose1Pct, data=data)
model

model2 = lm(TripsOver250PerCap ~ Dose1Pct + CarPct + log(AirportEnplanements+1), data=data)
model2

model2a = lm(TripsOver250PerCap ~ Dose1Pct + CarPct + AirportEnplanements + HispanicPct, data=data)
model2b = lm(TripsOver250PerCap ~ Dose1Pct + CarPct, data=data)

model3 = lm(TripsOver250PerCap ~ Dose1Pct + CarPct + IncomePerCap + log(AirportEnplanements+1) + BachelorsPct + WhitePct + BlackPct + IndigenousPct + HispanicPct + AsianPct, data=data)
model3

# model4 = lm(TripsOver250PerCap ~ CarPct + AirportEnplanements, data=data)
# model4


coeftest(model, vcov=vcovHC(model))
coeftest(model2, vcov=vcovHC(model2))
coeftest(model3, vcov=vcovHC(model3))

anova(model, model3, test = "F")
anova(model, model2, test = "F")

# 
# install.packages("Hmisc")
# library("Hmisc")
# data = drop_na(data)
# res2 <- rcorr(as.matrix(data))
# res2

plot(model2a, 1)
plot(model2b, 1)

plot(model2a, 3)
plot(model2b, 3)

data_residual <- broom::augment(model2a)

data_residual %>%
  ggplot()+
  aes(x=resid(model2a)) + 
  geom_histogram()



data_residual2 <- broom::augment(model2b)

data_residual2 %>%
  ggplot()+
  aes(x=resid(model2b)) + 
  geom_histogram()

# plot_resids_1 <- d %>% 
#   ggplot(aes(sample = resid(model2a))) + 
#   stat_qq() + stat_qq_line()
# 
# plot_resids_1
# 
# plot_resids_2 <- d %>% 
#   ggplot(aes(sample = resid(model2b))) + 
#   stat_qq() + stat_qq_line()
# 
# plot_resids_2

```